sudo: false
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  chrome: stable

env:
  - POLYMER=2
  - POLYMER=3

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm -q i && npm i -q --no-save bower polymer-cli && bower -q i &&
      npm run lint &&
      xvfb-run -s '-screen 0 1024x768x24' wct;
    fi

  - if [[ "$POLYMER" = "3" ]]; then
      npm --no-save -q install -g yarn bower magi-cli web-component-tester polymer-modulizer &&
      rm -rf node_modules &&
      magi p3-convert --out . --import-style=name &&
      yarn install --flat &&
      xvfb-run -s '-screen 0 1024x768x24' wct --npm;
    fi
