sudo: false
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  npm -q i && npm i -q --no-save bower polymer-cli && bower -q i &&
  npm run lint &&
  xvfb-run -s '-screen 0 1024x768x24' wct;
